title: 春和景明 · 个人文档
description: 个人研究、技术翻译、技术理解
baseurl: ""
url: ""
markdown: kramdown
kramdown:
  input: GFM
plugins: []
permalink: pretty
defaults:
  - scope:
      path: ""
    values:
      layout: page
collections: {}
